image: ghcr.io/marcelauliano/mitohifi:master
tasks:
- name: git clone
  command: |
    mkdir -p /workspace/examples
    cd /workspace/examples
    git clone https://github.com/marcelauliano/MitoHiFi
    unset JAVA_TOOL_OPTIONS
    bash
    
workspaceLocation: "/workspace"
