image: ghcr.io/marcelauliano/mitohifi:master
tasks:
- name: git clone
  command: |
    unset JAVA_TOOL_OPTIONS
    cd /workspace
vscode:
  extensions:
    - anwar.papyrus-pdf

workspaceLocation: "/workspace"
